import './globals.css';
import { Cormorant } from 'next/font/google';

const cormorant = Cormorant({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cormorant.className}>
      <body className="bg-[#EDEDED] text-[#32302D]">{children}</body>
    </html>
  );
}
